config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_registration' => 'omniauth_callbacks#finish_registration'
  end

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable do
      resources :comments, defaults: { commentable: 'answers' }
      patch 'set_best', on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  get '/search' => 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base

  include Attachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, class_name: 'User'

  scope :yesterdays, -> { where(created_at: Date.yesterday.to_time.all_day) }

  validates :title, :body, :user_id, presence: true

  after_create :subscribe_author
  before_save :store_hashtags

  def subscribe(user)
    subscribers << user unless subscribed? user
  end

  def unsubscribe(user)
    subscribers.delete(user) if subscribed? user
  end

  def subscribed?(user)
    subscribers.include? user
  end

  private

  def subscribe_author
    subscribe user
  end

  def store_hashtags
    return unless self.body_changed?
    hashtags_array = self.body.scan(/#\w*/).map(&:downcase).sort
    unless self.hashtags == hashtags_array
      #self.update_attributes(hashtags: hashtags_array)
      self.hashtags = hashtags_array
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource Question

  def index
    respond_with Question.all
  end

  def show
    respond_with Question.find(params[:id]), serializer: QuestionSerializer::Question
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question, only: [:edit, :update, :destroy, :subscribe, :unsubscribe]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  include Voted

  respond_to :js, :json

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = current_user.questions.new)
  end

  def edit
    if @question.nil?
      flash[:danger] = "You can not edit this question"
      redirect_to questions_path
    end
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(current_user.questions.destroy(@question), location: questions_path) #unless @question.nil?
  end

  def subscribe
    @question.subscribe current_user
    redirect_to @question
  end

  def unsubscribe
    @question.unsubscribe current_user
    redirect_to @question
  end

  private

  def load_question
    @question = Question.find_by(id: params[:id])
  end

  def build_answer
    @question = Question.find(params[:id])
    @answer = @question.answers.build
  end

  def publish_question
    PrivatePub.publish_to "/questions", question: QuestionPresenter.new(@question).to_json if @question.errors.empty?
  end

  def question_params
    params.require(:question)
          .permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def hashtag_links(text)
    text.gsub(/#\w*/) { |m| show_link m }
  end

  private

  def show_link(text)
    link_to text, search_path( query: { query: text, condition: "Tags" })
  end
end

app/views/questions/_form.html.slim
= simple_form_for question do |f|
  = f.input :title, label: 'Title'
  = f.input :body, label: 'Body'

  p Attachments:
  p
    /= f.simple_fields_for :attachments, question.attachments.build do |a|
    = f.simple_fields_for :attachments do |a|
      = render 'shared/attachment_fields', f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
    
    .btn = f.submit 'Create'

app/views/questions/_votes.html.slim
.row
  - cache [object, :vote]
    .col-md-2.question-votes-up 
      | Upvotes: #{object.votes.upvotes.rating}
    .col-md-2.question-votes-down 
      | Downvotes: #{object.votes.downvotes.rating}
    .col-md-2.question-votes-rating 
      | Rating: #{object.votes.rating}
  br
.row.question-votes-links
  /- if user_signed_in? && !(current_user.id == object.user_id)
  - if can? :vote, object
    - if object.voted_for? current_user
      .col-md-2
        = link_to 'Reset', vote_reset_question_path(@question), method: :patch, remote: true, data: {type: :json}
    - else
      .col-md-2
        = link_to 'Up', vote_up_question_path(@question), method: :patch, remote: true, data: {type: :json}
      .col-md-2
        = link_to 'Down', vote_down_question_path(@question), method: :patch, remote: true, data: {type: :json}
hr

app/views/questions/edit.html.slim
h3 Edit card
= render 'form', question: @question
= link_to 'Back', questions_path

app/views/questions/index.html.slim
h3 Questions 
hr

.question-list
  - cache collection_cache_key_for :question do
    - @questions.each do |question|  
      .row.question id="#{dom_id(question)}"
        .col-md-1
          = question.votes.count
          br
          | votes
        .col-md-1
          = question.answers.count
          br
          | answers
        .col-md-6
          = link_to question.title, question
      hr

.row
  /- if user_signed_in?
  - if can? :create, Question
    = link_to 'Ask question', new_question_path

= subscribe_to "/questions"

app/views/questions/new.html.slim
h3 New question
= render 'form', question: @question
= link_to 'Back', questions_path

app/views/questions/show.html.slim
.question id="#{dom_id(@question)}"
  - cache @question do
    h3
      = @question.title
    hr
    /= @question.body
    == hashtag_links(@question.body)
    hr
    .question-attachments
      p Attachments:
      ul 
        -@question.attachments.each do |a|
          li = link_to a.file.identifier, a.file.url
  br
.row
  - if can? :manage, @question
    .col-md-1
      =<> link_to 'Edit', edit_question_path(@question)
    .col-md-1
      =<> link_to 'Delete', @question, data: { confirm: 'Sure?' }, method: :delete
  .col-md-1
    = link_to 'Back', questions_path
hr
.question-votes
  = render 'votes', object: @question 

.question-subscribe
  - if can? :subscribe, @question
    = link_to 'Subscribe', subscribe_question_path(@question), method: :post
  - if can? :unsubscribe, @question
    = link_to 'Unsubscribe', unsubscribe_question_path(@question), method: :post

hr
.question-comments
  ul.question-comments-list
    = render @question.comments
  - if can? :create, Comment
    = render 'comments/form', comment: @question.comments.new, commentable: @question

.container-fluid
  - if @question.answers.any?
    h4 #{@question.answers.count} Answers
    .answers data={question_id: "#{@question.id}"}
      = render @question.answers

  - if can? :create, Answer
    = render 'answers/form', question: @question, answer: @answer

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"