config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_registration' => 'omniauth_callbacks#finish_registration'
  end

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable do
      resources :comments, defaults: { commentable: 'answers' }
      patch 'set_best', on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  get '/search' => 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource

  def search
    outcome = Search.run(params[:query])
    outcome.valid? ? @results = outcome.result : @results = []
    respond_with @results
  end
end

app/views/search/_answer.html.slim
h4 Answer
div
  = link_to answer.body.truncate(100), question_path(answer.question_id)

app/views/search/_comment.html.slim
h4 Comment
div
  - if comment.commentable.is_a? Question
    = link_to comment.body.truncate(100), question_path(comment.commentable)

  - if comment.commentable.is_a? Answer
    = link_to comment.body.truncate(100), question_path(comment.commentable.question)

app/views/search/_form.html.slim
.row
  .col-md-4
    = simple_form_for :query, url: search_path, method: :get do |f|
      = f.input :query
      = f.input :condition, priority: ["Everywhere"], collection: %w(Everywhere Questions Answers Comments Users Tags)

      .btn = f.submit 'Search'

app/views/search/_question.html.slim
h4 Question
div
  p = link_to question.title, question_path(question)

app/views/search/_user.html.slim
h4 User
div
  = user.email

app/views/search/search.html.slim
.search_results
  - if @results.any?
    h4 Search results
    - @results.each do |result|
      = render partial: "#{result.class.name.downcase}", object: result
  - else
    h4 Anything found