config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_registration' => 'omniauth_callbacks#finish_registration'
  end

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable do
      resources :comments, defaults: { commentable: 'answers' }
      patch 'set_best', on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  get '/search' => 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  include Attachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true

  default_scope -> { order(is_best: :desc).order(created_at: :asc) }

  #after_create :notify_subscribers
  after_commit :notify_subscribers

  def set_best
    ActiveRecord::Base.transaction do
      question.answers.update_all is_best: false
      update!(is_best: true)
    end
  end

  private

  def notify_subscribers
    NotifySubscribersJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question
  before_action :load_answer, only: [:edit, :update, :destroy, :set_best]
  after_action :publish_answer, only: :create

  include Voted

  respond_to :js, :json

  authorize_resource

  def create
    respond_with(@answer = current_user.answers.create(answer_params.merge(question: @question)), location: question_path(@question))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    respond_with(@answer.destroy) #if @answer.user == current_user
  end

  def set_best
    @answer.set_best if @question.user == current_user
    flash.now[:success] = "Your best answer successfully selected"
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = @question.answers.find_by(id: params[:id])
  end

  def publish_answer
      PrivatePub.publish_to "/questions/#{@question.id}/answers", answer: render_to_string('answers/show.json.jbuilder') if @answer.errors.empty?
  end

  def answer_params
    params.require(:answer)
      .permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource Answer

  before_action :load_question, only: [:index, :create]

  def index
    respond_with @question.answers
  end

  def show
   respond_with Answer.find(params[:id]), serializer: AnswerSerializer::Answer
  end

  def create
    respond_with @question.answers.create(answer_params.merge(user: current_resource_owner)), location: question_path(@question)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.id.present?
  .row.answer data={answer_id: "#{answer.id}"}
    div id="answer-id-#{answer.id}"
      - cache answer do
        - if answer.is_best?
          h4 The best answer 
        p = answer.body
        - if answer.attachments.any?
          p Attachments:
          ul
            - answer.attachments.each do |a|
              li = link_to a.file.identifier, a.file.url
      hr
      .answer-votes id="#{dom_id(answer)}"
          = render 'answers/votes', object: answer
      .row
        - if can? :manage, answer
          = simple_form_for [@question, answer],
            remote: true,
            html: { class: 'answer-edit', id: "edit-answer-#{answer.id}" } do |f|
            = f.input :body, label: 'Answer'
            p Attachments:
            p
              = f.simple_fields_for :attachments do |a|
                = render 'shared/attachment_fields', f: a
              .links
                = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
            .btn = f.submit 'Save'
          .col-md-1
            = link_to 'Edit', '',
                class: 'edit-answer-link',
                data: { answer_id: answer.id }
          .col-md-1
            = link_to 'Delete', 
                [answer.question, answer], 
                remote: true,
                method: :delete
        - if can?(:set_best, answer) && !answer.is_best?
          .col-md-1
            = link_to 'Best answer', 
              set_best_question_answer_path(question_id: answer.question, id: answer),
                method: :patch,
                remote: true,
                id: "set-best-link-#{answer.id}"
      hr
      .answer-comments
        .ul.answer-comments-list
          = render answer.comments
        - if can? :create, Comment
          .answer-new-comment = render 'comments/answer_form', question: @question, comment: answer.comments.new, commentable: answer

app/views/answers/_form.html.slim
= simple_form_for [question, answer], remote: true do |f|
  .answer-input-body = f.input :body, label: 'Body'
  p Attachments:
  p
    = f.simple_fields_for :attachments, answer.attachments.build do |a|
      = render 'shared/attachment_fields', f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
  .btn = f.submit 'Add answer'

app/views/answers/_votes.html.slim
.row
  - cache [object, :vote]
    .col-md-2.answer-votes-up 
      | Upvotes: #{object.votes.upvotes.rating}
    .col-md-2.answer-votes-down 
      | Downvotes: #{object.votes.downvotes.rating}
    .col-md-2.answer-votes-rating 
      | Rating: #{object.votes.rating}
  br
.row.answer-votes-links
  - if can? :vote, object
    - if object.voted_for? current_user
      .col-md-2
        = link_to 'Reset', vote_reset_question_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true
    - else
      .col-md-2
        = link_to 'Up', vote_up_question_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true
      .col-md-2
        = link_to 'Down', vote_down_question_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true
hr

app/views/answers/create.js.erb
<% if @answer.valid? %>
  $('.answers').append('<%= j render 'answer', answer: @answer %>');
  $('form#new_answer div textarea').val('');
  $(".nested-fields :not(:first)").remove();
<% end %>

$('.notice').html('<%= j render partial: 'shared/notice'  %>');

app/views/answers/create21.js.erb
<% if @answer.valid? %>
  $('.answers').append('<%= j render 'answer', answer: @answer %>');
  $('form#new_answer div textarea').val('');
  $(".nested-fields :not(:first)").remove();
  <% publish_to "/questions/#{@question.id}/answers" do %>
    $('.answers').append('<%= j render 'answer', answer: @answer %>');
  <% end %>
<% end %>

$('.notice').html('<%= j render partial: 'shared/notice'  %>');

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('div#answer-id-<%= @answer.id %>').remove();
<% end %>

$('.notice').html('<%= j render partial: 'shared/notice'  %>');

app/views/answers/edit.html.slim
h3 Edit answer
= simple_form_for [@question, @answer] do |f|
  = f.input :body, label: 'Body'
  .btn = f.submit 'Add answer'
/= render 'form', question: @question, answer: @answer
= link_to 'Back', question_path(@question)

app/views/answers/new.html.slim
h3 New answer
= render 'form', question: @question, answer: @answer
= link_to 'Back', question_path(@question)

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @question.answers %>')

$('.notice').html('<%= j render partial: 'shared/notice' %>');

app/views/answers/update.js.erb
<% if @answer.valid? %>
  $('div#answer-id-<%= @answer.id %>').html('<%= j render @answer %>')
<% end %>

$('.notice').html('<%= j render partial: 'shared/notice'  %>');